version: '3.5'
services:
  
  user-db:
    build: user-postgresql
    image: user_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USER}
    networks:
      - fitness_ntwrk

  product-db:
    build: product-postgresql
    image: product_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PRODUCT}
    networks:
      - fitness_ntwrk

  mail-db:
    build: mail-postgresql
    image: mail_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_MAIL}
    networks:
      - fitness_ntwrk

  pgadmin:
    build: pgadmin
    image: fitness_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - fitness_ntwrk

  user-service:
    build: user-service
    image: user-service:1.0.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_USER}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - fitness_ntwrk

  product-service:
    build: product-service
    image: product-service:1.0.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_PRODUCT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8080"
    networks:
      - fitness_ntwrk

  mail-service:
    build: mail-service
    image: mail-service:1.0.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_MAIL}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_CONFIRMATION_LINK: ${MAIL_CONFIRMATION_LINK}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8082:8080"
    networks:
      - fitness_ntwrk

  eureka-server:
    build: eureka-server
    image: eureka-server:1.0.0
    ports:
      - "8761:8761"
    networks:
      - fitness_ntwrk
  
  swagger-ui:
    build: swagger-ui
    image: fitness_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - fitness_ntwrk

  proxy:
    build: proxy
    image: fitness_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - fitness_ntwrk

networks:
    fitness_ntwrk:
      name: fitness_ntwrk