version: '3.5'
services:
  
  user-db:
    build: user-postgresql
    image: user_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USER}
    networks:
      - fitness_ntwrk

  product-db:
    build: product-postgresql
    image: product_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PRODUCT}
    networks:
      - fitness_ntwrk

  mail-db:
    build: mail-postgresql
    image: mail_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_MAIL}
    networks:
      - fitness_ntwrk

  audit-db:
    build: audit-postgresql
    image: audit_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_AUDIT}
    networks:
      - fitness_ntwrk

  report-db:
    build: report-postgresql
    image: report_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_REPORT}
    networks:
      - fitness_ntwrk

  pgadmin:
    build: pgadmin
    image: fitness_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - fitness_ntwrk

  user-service:
    build: user-service
    image: user-service:1.0.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_USER}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    networks:
      - fitness_ntwrk

  product-service:
    build: product-service
    image: product-service:1.0.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_PRODUCT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    networks:
      - fitness_ntwrk

  mail-service:
    build: mail-service
    image: mail-service:1.0.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_MAIL}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_CONFIRMATION_LINK: ${MAIL_CONFIRMATION_LINK}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    networks:
      - fitness_ntwrk

  audit-service:
    build: audit-service
    image: audit-service:1.0.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_AUDIT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
    networks:
      - fitness_ntwrk

  report-service:
    build: report-service
    image: report-service:1.0.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_REPORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
    networks:
      - fitness_ntwrk

  eureka-server:
    build: eureka-server
    image: eureka-server:1.0.0
    ports:
      - "8761:8761"
    networks:
      - fitness_ntwrk

  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    volumes:
      - ./data:/data
    command: server /data --console-address :9001

  swagger-ui:
    build: swagger-ui
    image: fitness_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - fitness_ntwrk

  proxy:
    build: proxy
    image: fitness_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - fitness_ntwrk

networks:
    fitness_ntwrk:
      name: fitness_ntwrk