spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL_REPORT}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: report-service

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${KAFKA_SERVERS}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8000
    miscellaneous:
      allow-anonymous-data-usage: false
    jobs:
      retry-back-off-time-seed: 1
    database:
      table-prefix: app.

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

minio:
  server-url: ${MINIO_SERVER_URL}
  secret-key: ${MINIO_SECRET_KEY}
  access-key: ${MINIO_ACCESS_KEY}
  excel-bucket: ${MINIO_EXCEL_BUCKET}
